name: tavernup_domain
description: Shared domain models and interfaces for TavernUp.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  test: ^1.24.0