name: tavernup_repositories_supabase
description: Supabase repository implementations for TavernUp.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  tavernup_domain:
    path: ../tavernup_domain
  supabase: ^2.0.0

dev_dependencies:
  test: ^1.24.0
  dotenv: ^4.2.0
