name: tavernup_server
description: Backend worker service for TavernUp.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  tavernup_domain:
    path: ../tavernup_domain
  tavernup_repositories_supabase:
    path: ../tavernup_repositories_supabase
  tavernup_process_camunda:
    path: ../tavernup_process_camunda
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.0
  dio: ^5.0.0
  supabase: ^2.0.0

dev_dependencies:
  test: ^1.24.0